<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stock [
    <!ELEMENT stock (new-car+,used-car+)>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ATTLIST model name CDATA #REQUIRED>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>
]>
<stock>
    <new-car>
        <model name="A1"/>
        <price>28000</price>
    </new-car>
    <new-car>
        <model name="A2"/>
        <price>48000</price>
    </new-car>
    <used-car>
        <model name="Nissan Sunny"/>
        <price>12000</price>
        <mileage>75000</mileage>
        <condition>Good</condition>
    </used-car>

    <used-car>
        <model name="Toyota Yaris"/>
        <price>10000</price>
        <mileage>95000</mileage>
        <!-- condition omitted -->
    </used-car>
</stock>