<?xml version="1.0" encoding="UTF"?>
<!DOCTYPE stock[
    <!ELEMENT stock (new-car+,used-car+)>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>



]>

<stock>
    <new-car>
        <model>A1</model>
        <price>100</price>
    </new-car>   
    <new-car>
        <model>A2</model>
        <price>200</price>
    </new-car>
    <used-car>
        <model>Nissan Sunny</model>
        <price>12000</price>
        <mileage>85000</mileage>
        <condition>Good</condition>
    </used-car>
    <used-car>
        <model>Ford Focus</model>
        <price>10000</price>
        <mileage>95000</mileage>
    </used-car>
</stock>
