<?xml version="1.0" encoding="UTF"?>
<!DOCTYPE stock[
    <!ELEMENT stock (new-car+,used-car+)>
    <!ELEMENT new-car (model,price)>
    <!ELEMENT used-car (model,price,mileage,condition?)>
    <!ELEMENT model EMPTY>
    <!ATTLIST model name CDATA #REQUIRED>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT mileage (#PCDATA)>
    <!ELEMENT condition (#PCDATA)>



]>

<stock>
    <new-car>
        <model name="A1"/>
        <price>100</price>
    </new-car>   
    <new-car>
        <model name="A2"/>
        <price>200</price>
    </new-car>
    <used-car>
        <model name="Nissan Sunny"/>
        <price>12000</price>
        <mileage>85000</mileage>
        <condition>Good</condition>
    </used-car>
    <used-car>
        <model name="Ford Focus"/>
        <price>10000</price>
        <mileage>95000</mileage>
    </used-car>
</stock>
